---
format_version: '24'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: flutter
meta:
  bitrise.io:
    machine_type_id: g2.mac.medium
    stack: osx-xcode-16.3.x
pipelines:
  build-and-test:
    triggers:
      pull_request:
      - source_branch: "*"
    workflows:
      init: {}
      test:
        depends_on:
        - init
      build_sample:
        depends_on:
        - init
  deploy:
    triggers:
      tag:
      - name:
          regex: "^\\d+\\.\\d+\\.\\d+$"
    workflows:
      init: {}
      publish_to_pub_dev:
        depends_on:
        - init
workflows:
  init:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
        inputs:
        - verbose: 'true'
    - git-clone@8: {}
    - flutter-installer@1:
        inputs:
        - version: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.27.3-stable.zip
    - save-dart-cache: {}
    - deploy-to-bitrise-io@2:
        inputs:
        - pipeline_intermediate_files: "$BITRISE_SOURCE_DIR:BITRISE_SOURCE_DIR"
  test:
    steps:
    - pull-intermediate-files@1:
        inputs:
        - artifact_sources: init
    - restore-dart-cache@2: {}
    - flutter-analyze@0:
        inputs:
        - project_location: "$BITRISE_SOURCE_DIR"
    - flutter-test@1:
        inputs:
        - project_location: "$BITRISE_SOURCE_DIR"
  build_sample:
    steps:
    - pull-intermediate-files@1:
        inputs:
        - artifact_sources: init
    - restore-dart-cache: {}
    - flutter-build@0:
        inputs:
        - project_location: "$BITRISE_SOURCE_DIR/example"
  publish_to_pub_dev:
    steps:
    - pull-intermediate-files@1:
        inputs:
        - artifact_sources: init
    - script@1:
        title: Publish to pub.dev
        inputs:
        - content: dart pub publish
